#' Performs a fast continuous wavelet transform
#'
#' This function call is a thin wrapper for the fcwt API.
#'
#' @param signal
#'  Real-valued time series. The time step gaps are assumed to be uniform.
#'
#' @param sample_freq
#'  Sampling rate of input time series in Hz.
#'  (to establish a connection to physical units.)
#'  The sampling rate also defines the highest possible
#'  frequency resolution of the CWT: half of the sampling rate.
#'
#' @param freq_begin
#'  Sets the minimal frequency (`> 0`!) in Hz that should be
#'  contained in the output.
#'
#' @param freq_end
#'  Sets the maximal frequency (`> freq_begin`!) in Hz that should be
#'  contained in the output.
#'
#' @param n_freqs
#'  Number of frequency bins generated by the CWT. The frequencies
#'  are linearly distributed. Computation time increases
#'  when raising the number of frequency bins.
#'
#' @param sigma
#'  Sets a parameter modifying the wavelet length. Adjusts
#'  the time/frequency uncertainty balance. Defaults to 1.
#'  Larger (lower) value of sigma corresponds to a better
#'  (worse) frequency resolution and a worse (better) time
#'  resolution.
#'
#' @param abs
#'  Should the output return the only the absolute values of the transform?
#'  `TRUE` / `FALSE`.
#'
#' @param nthreads
#'  Number of threads used by the computation, if applicable.
#'
#' @return
#'  A numeric matrix with `dim = c(length(signal), n_freqs)`. The matrix is
#'  real-valued if `abs = TRUE`, otherwise complex-valued.
#'
#' @examples
#' ts_sin_440 <- sin((1:44100) * 2 * pi * 440 / 44100)
#'
#' fcwt(
#'   ts_sin_440,
#'   sample_freq = 44100,
#'   freq_begin = 50,
#'   freq_end = 1000,
#'   n_freqs = 10,
#'   sigma = 5
#' )
#'
#' @export
fcwt <- function(signal,
                 sample_freq,
                 freq_begin,
                 freq_end,
                 n_freqs,
                 sigma,
                 # abs = FALSE,
                 remove_coi = TRUE,
                 nthreads = 8L) {
  stopifnot(is.numeric(signal))
  stopifnot(is.numeric(sample_freq), sample_freq > 0)
  stopifnot(is.numeric(freq_begin), freq_begin > 0)
  stopifnot(is.numeric(freq_end), freq_end > freq_begin)
  stopifnot(is.numeric(n_freqs), n_freqs > 0)
  stopifnot(is.numeric(sigma), sigma > 0)
  stopifnot(is.numeric(nthreads))
  # stopifnot(is.logical(abs))

  output <-
    fcwt_raw(
      signal, as.integer(sample_freq), freq_begin, freq_end, as.integer(n_freqs),
      sigma, as.integer(nthreads), FALSE,
      abs = TRUE
    )

  # if (!abs) {
  #   dim(output) <- c(length(signal), n_freqs, 2)
  #
  #   output <- output[, , 1] + output[, , 2] * 1i
  # } else {
  dim(output) <- c(length(signal), n_freqs)
  # }

  new_fcwtr_scalogram(
    output, sample_freq, freq_begin, freq_end, sigma, remove_coi
  )
}
